spring.application.name=ProyectoTienda
server.port=8080
spring.datasource.url=jdbc:mysql://localhost:3306/TiendaB2_IN5CM?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

